model:
  pretrained_model_path: "./GMTS/model/Qwen2.5-Math-1.5B"
  device: "cuda:7"
  dtype: "bfloat16"
  old_model_device: "cuda:0"

data:
  data_name: 'math'
  training_path: "./GMTS/GMTS-Framework1/test_data/math-500"
  testing_path: "./GMTS/GMTS-Framework1/test_data/math-500"
  test_size: 500

testing:
  batch_size:     125  

training:
  method:         "dapo"    
  random_seed:      0
  max_prompt_len:  1024
  max_gen_len:     2048

  batch_size              :  1024   # 512*16
  num_questions_per_batch :  64     # 一个step多少个question

  rollout_mini_batch      :  16     # rollout的时候, 每次走多少个question?
  mini_batch_size         :  64     # update的时候每次update过多少个question?
  micro_batch_size        :  4      # update的时候每次update计算几个? 
  kl_beta                 :  0.001  # kl-coef

  learning_rate: 3.0e-5             
  ckpt_dir: "./GMTS/GMTS-Framework1/result/ckpt_dir/Qwen2.5-math-1.5b-dapo"
  log_dir: "./GMTS/GMTS-Framework1/result/log_dir/Qwen2.5-math-1.5b-dapo"

  save_logp_gradient_path: ./GMTS/GMTS-Framework1/result/gradient_dir/Qwen2.5-math-1.5b-dapo/
  save_true_gradient_path: ./GMTS/GMTS-Framework1/result/gradient_dir/Qwen2.5-math-1.5b-dapo/
  save_entrpy_path: ./GMTS/GMTS-Framework1/result/gradient_dir/Qwen2.5-math-1.5b-dapo/
  save_mask_path: ./GMTS/GMTS-Framework1/result/gradient_dir/Qwen2.5-math-1.5b-dapo/
  save_adv_pth: ./GMTS/GMTS-Framework1/result/gradient_dir/Qwen2.5-math-1.5b-dapo/
  save_prefix_pth: ./GMTS/GMTS-Framework1/result/gradient_dir/Qwen2.5-math-1.5b-dapo/
  save_ids_path: ./GMTS/GMTS-Framework1/result/gradient_dir/Qwen2.5-math-1.5b-dapo/
  
  ckpt_save_interval: 200
  gradient_interval : 100
  eval_interval     : 10             # 每10步进行一次eval,一共188个step

  # Number of examples per gradient accumulation step
  max_grad_norm: 1.0
  weight_decay: 0.0
  betas: [0.9, 0.999]
  memory_efficient_adamw: false
  
  clip_ratio_low       :   0.20  # low
  clip_ratio_high      :   0.28  # high
  use_entropy          :   false 
  selected_percent     :   0.0    
  use_TES_method       :   false 
  use_GMTS_method      :   false 
  read_model_path      :   ""    
  doing_inverse        :   false 
  use_filter           :   false